github:
  prebuilds:
    addComment: false
    addBadge: true

ports:
  - port: 8080
  - port: 7471

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker

image:
  file: .gitpod.Dockerfile

# startup tasks
tasks:
  - name: 'Maven dependencies'
    init: ./mvnw package -DskipTests
  - name: 'Npm dependencies'
    init: npm ci
